interface IWhoIs {
  msg?: string
  dName?: string
  sRegistrator?: string
  dStatus?: string
  sNs1?: string
  sNs2?: string
  sNs3?: string
  sNs4?: string
  dActivated?: string
  dExpired?: string
  sOrg?: string
  sCustomer?: string
  sCustomerPhone?: string
  sCustomerFax?: string
  sCustomerEMail?: string
  sCustomerPost?: string
  sCustomerAddress?: string
  sCustomerCity?: string
  sCustomerRegion?: string
  sCustomerCountry?: string
  sCustomerState?: string
  sAdminsNameRU?: string
  sAdminsOrgRU?: string
  sAdminsPhone?: string
  sAdminsFax?: string
  sAdminsEMail?: string
  sAdminsPost?: string
  sAdminsAddressRU?: string
  sAdminsCityRU?: string
  sAdminsRegion?: string
  sAdminsCountryRU?: string
  sAdminsState?: string
  sTechsNameRU?: string
  sTechsOrgRU?: string
  sTechsPhone?: string
  sTechsFax?: string
  sTechsEMail?: string
  sTechsPost?: string
  sTechsAddressRU?: string
  sTechsCityRU?: string
  sTechsRegion?: string
  sTechsCountryRU?: string
  sTechsState?: string
  sBillsNameRU?: string
  sBillsOrgRU?: string
  sBillsPhone?: string
  sBillsFax?: string
  sBillsEMail?: string
  sBillsPost?: string
  sBillsAddressRU?: string
  sBillsCityRU?: string
  sBillsRegion?: string
  sBillsCountryRU?: string
  sBillsState?: string
  rcode?: string
}
